#include "Components.h"

using namespace vkpbrt;

REGISTER_COMPONENT_TYPE(Transform)
REGISTER_COMPONENT_TYPE(Camera)
REGISTER_COMPONENT_TYPE(Material)
REGISTER_COMPONENT_TYPE(Mesh)
REGISTER_COMPONENT_TYPE(Behavior)